<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Forms\CampaignFormView
 */
?>
<?= $this->getForm()->open() ?>
<?= $this->getForm()->token() ?>
<?= $this->getForm()->formNameInput() ?>
<div class="control-group <?= $this->referenceError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-reference">
    <?= $this->getReferenceLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getReference(); ?>
    <?php if($this->referenceError()): ?>
    <span class="help-inline">
      <?= $this->getReferenceError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group <?= $this->nameError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-name">
    <?= $this->getNameLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getName(); ?>
    <?php if($this->nameError()): ?>
    <span class="help-inline">
      <?= $this->getNameError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group <?= $this->descriptionError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-descirption">
    <?= $this->getDescriptionLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getDescription(); ?>
    <?php if($this->descriptionError()): ?>
    <span class="help-inline">
      <?= $this->getDescriptionError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group <?= $this->typeError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-type">
    <?= $this->getTypeLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getType(); ?>
    <?php if($this->typeError()): ?>
    <span class="help-inline">
      <?= $this->getTypeError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group <?= $this->sendTypeError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-send-type">
    <?= $this->getSendTypeLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getSendType(); ?>
    <?php if($this->sendTypeError()): ?>
    <span class="help-inline">
      <?= $this->getSendTypeError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group <?= $this->contactIdError() ? "error" : "" ?>">
  <label class="control-label" for="form-campaign-contact-id">
    <?= $this->getContactIdLabel() ?>
  </label>
  <div class="controls">
    <?= $this->getContactId(); ?>
    <?php if($this->contactIdError()): ?>
      <span class="help-inline">
      <?= $this->getContactIdError() ?>
    </span>
    <?php endif; ?>
  </div>
</div>
<div class="control-group form-inline">
  <label class="control-label" for="form-campaign-active">
    <?= $this->getActiveLabel(); ?>
  </label>
  <div class="controls">
    <?= $this->getActive(); ?>
  </div>
</div>
<div class="control-group form-inline">
  <div class="controls clearfix">
    <button type="submit" class="btn js-btn-loading"
            data-loading-text="Submitting">
      <?= $this->getSubmit()->data() ?>
    </button>
  </div>
</div>
<?= $this->getForm()->close() ?>
