<?php
/**
 * @author gareth.evans
 *
 * @var $this     \Qubes\Defero\Applications\Defero\Views\Stats\StatsView
 * @var $campaign \Qubes\Defero\Components\Campaign\Mappers\Campaign
 */

$relDate = $this->relativeDate ? strtotime($this->relativeDate) : time();

$day1From = (new DateTime())->setTimestamp(strtotime('today 00:00', $relDate));
$day1To = (new DateTime())->setTimestamp(strtotime('today 23:59', $relDate));
$day2From = (new DateTime())->setTimestamp(strtotime('-1 day 00:00', $relDate));
$day2To = (new DateTime())->setTimestamp(strtotime('-1 day 23:59', $relDate));
$day3From = (new DateTime())->setTimestamp(strtotime('-2 day 00:00', $relDate));
$day3To = (new DateTime())->setTimestamp(strtotime('-2 day 23:59', $relDate));
$day4From = (new DateTime())->setTimestamp(strtotime('-3 day 00:00', $relDate));
$day4To = (new DateTime())->setTimestamp(strtotime('-3 day 23:59', $relDate));
?>
<div>
  <div>
    <form method="post"><input type="text" name="date"><input type="submit">
    </form>
  </div>
  <table class="table table-striped table-bordered table-hover table-href">
    <thead>
    <tr>
      <th rowspan="2" colspan="2">Campaign</th>
      <th colspan="3"><?php echo $day4From->format('d M Y'); ?></th>
      <th colspan="3"><?php echo $day3From->format('d M Y'); ?></th>
      <th colspan="3"><?php echo $day2From->format('d M Y'); ?></th>
      <th colspan="3"><?php echo $day1From->format('d M Y'); ?></th>
    </tr>
    <tr>
      <th>Q</th>
      <th>S</th>
      <th>F</th>
      <th>Q</th>
      <th>S</th>
      <th>F</th>
      <th>Q</th>
      <th>S</th>
      <th>F</th>
      <th>Q</th>
      <th>S</th>
      <th>F</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->campaigns as $campaign)
    {
      echo '<tr>';
      echo '<td>' . $campaign->id() . '</td>';
      echo '<td>' . $campaign->name . '</td>';

      $stats = $campaign->getStats($day4From, $day4To);
      echo '<td>' . number_format($stats->queued) . '</td>';
      echo '<td>' . number_format($stats->sent) . '</td>';
      echo '<td>' . number_format($stats->failed) . '</td>';
      $stats = $campaign->getStats($day3From, $day3To);
      echo '<td>' . number_format($stats->queued) . '</td>';
      echo '<td>' . number_format($stats->sent) . '</td>';
      echo '<td>' . number_format($stats->failed) . '</td>';
      $stats = $campaign->getStats($day2From, $day2To);
      echo '<td>' . number_format($stats->queued) . '</td>';
      echo '<td>' . number_format($stats->sent) . '</td>';
      echo '<td>' . number_format($stats->failed) . '</td>';
      $stats = $campaign->getStats($day1From, $day1To);
      echo '<td>' . number_format($stats->queued) . '</td>';
      echo '<td>' . number_format($stats->sent) . '</td>';
      echo '<td>' . number_format($stats->failed) . '</td>';
      echo '</tr>';
    }
    ?>
    </tbody>
  </table>
</div>
