<?php
/**
 * @author gareth.evans
 *
 * @var $this     \Qubes\Defero\Applications\Defero\Views\Stats\StatsView
 * @var $campaign \Qubes\Defero\Components\Campaign\Mappers\Campaign
 */
use \Cubex\Helpers\DateTimeHelper;

$day1From = DateTimeHelper::dateTimeFromAnything('today 00:00');
$day1To = DateTimeHelper::dateTimeFromAnything('today 23:59');
$day2From = DateTimeHelper::dateTimeFromAnything('-1 day 00:00');
$day2To = DateTimeHelper::dateTimeFromAnything('-1 day 23:59');
$day3From = DateTimeHelper::dateTimeFromAnything('-2 days 00:00');
$day3To = DateTimeHelper::dateTimeFromAnything('-2 days 23:59');
?>
<div>
  <table class="table table-striped table-bordered table-hover table-href">
    <thead>
    <tr>
      <th rowspan="2" colspan="2">Campaign</th>
      <th colspan="3"><?php echo $day3From->format('d M Y'); ?></th>
      <th colspan="3"><?php echo $day2From->format('d M Y'); ?></th>
      <th colspan="3"><?php echo $day1From->format('d M Y'); ?></th>
    </tr>
    <tr>
      <th>Queued</th>
      <th>Sent</th>
      <th>Failed</th>
      <th>Queued</th>
      <th>Sent</th>
      <th>Failed</th>
      <th>Queued</th>
      <th>Sent</th>
      <th>Failed</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->campaigns as $campaign)
    {
      echo '<tr>';
      echo '<td>' . $campaign->id() . '</td>';
      echo '<td>' . $campaign->name . '</td>';

      $stats = $campaign->getStats($day3From, $day3To);
      echo '<td>' . $stats->queued . '</td>';
      echo '<td>' . $stats->sent . '</td>';
      echo '<td>' . $stats->failed . '</td>';
      $stats = $campaign->getStats($day2From, $day2To);
      echo '<td>' . $stats->queued . '</td>';
      echo '<td>' . $stats->sent . '</td>';
      echo '<td>' . $stats->failed . '</td>';
      $stats = $campaign->getStats($day1From, $day1To);
      echo '<td>' . $stats->queued . '</td>';
      echo '<td>' . $stats->sent . '</td>';
      echo '<td>' . $stats->failed . '</td>';
      echo '</tr>';
    }
    ?>
    </tbody>
  </table>
</div>
