<?php
/**
 * @author tom.kay
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignSourceView
 */
?>
<style>
  .controls.control-group label { display: inline-block; margin-right: 10px; white-space: nowrap; }

  .controls.control-group label input { margin: 0 5px 0 0; }
</style>
<div class="wrappedContent">
  <div>
    <h2 class="text-center">
      Configure Data Source
    </h2>
  </div>
  <?= $this->form ?>
</div>
