<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignsView
 */
?>
<div class="wrappedContent">
  <div>
    <div class="pull-right">
      <a href="/campaigns/new" class="btn btn-primary btn-small">
        New Campaign
      </a>
    </div>
    <?= $this->campaignsSearch ?>
  </div>
  <div>
    <table id="campaigns" class="table table-striped table-bordered table-hover table-href">
      <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Subject</th>
        <th>Send Type</th>
        <th>Label</th>
        <th>Active</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <?php foreach($this->campaigns as $campaign): ?>
        <tr data-href="/campaigns/<?= $campaign->id() ?>"
            data-cid="<?= $campaign->id() ?>"
            class="js-href"
            title="View <?= $campaign->name ?> (<?= $campaign->dataSource ?>)">
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>"
               title="View <?= $campaign->name ?> (<?= $campaign->dataSource ?>)">
              #<?= $campaign->id() ?>
            </a>
          </td>
          <td><?= $campaign->name ?></td>
          <td><?= $campaign->message()->subject ?></td>
          <td><?= $campaign->getTitledSendType() ?></td>
          <td><?= $campaign->label ?></td>
          <td><?= $campaign->active ? "Yes" : "No" ?></td>
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>/edit"
               title="Edit <?= $campaign->name ?>">
              <i class="icon-edit"></i></a>
            <a href="/campaigns/<?= $campaign->id() ?>/clone"
               title="Clone <?= $campaign->name ?>">
              <i class="icon-download-alt"></i>
               </a>
            <a href="/campaigns/<?= $campaign->id() ?>/delete"
               title="Delete <?= $campaign->name ?>"
               class="js-popover"
               data-content="<?= $this->getDeletePopover($campaign->id()) ?>"
               data-html="true"
               data-prevent-default="true"
               data-placement="left">
              <i class="icon-trash"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
</div>
