<?php
/**
 * @author tom.kay
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignMessageView
 */
?>
<div class="wrappedContent">
  <div class="pull-right btn-toolbar">
    <div class="btn-group">
      <?php
      if($this->message->language() !== 'en')
      {
        $url = '/campaigns/' . $this->message->campaignId .
          '/message/' . $this->message->language() .
          '/translate';
        echo '<a href="' . $url . '" class="btn btn-primary js-popover"
           title="Translate Message"
           data-content="This will overwrite the current message.&lt;br&gt;'
          . $this->getConfirmPopover($url)
          . '"
           data-container="body"
           data-placement="bottom" data-html="true"
           data-prevent-default="true">Translate</a>';
      }
      ?>
    </div>
    <div class="btn-group">
      <?php
      foreach($this->languages as $code)
      {
        ?>
        <a href="/campaigns/<?=
        $this->message->campaign()->id() ?>/message/<?= $code ?>"
           title="Edit <?= $this->message->campaign()->name . ' ' . $code ?>"
           class="btn btn-<?=
           $code == $this->message->language()
             ? 'success' : 'info'; ?>"><?= $code ?></a>
      <?
      }
      ?>
    </div>
  </div>
  <div>
    <h2 class="text-center">
      Compose <?= $this->message->campaign()->name ?>
    </h2>
  </div>
  <?= $this->form ?>
</div>
