<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignView
 */
use \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignProcessorsView;

$ds = $this->campaign->getDataSource();
?>
<div class="wrappedContent">
  <div class="pull-right btn-toolbar">
    <div class="btn-group">
      <a href="/campaigns/<?= $this->campaign->id() ?>/edit"
         title="Edit <?= $this->campaign->name ?>"
         class="btn btn-info">Edit</a>
      <a href="/campaigns/<?= $this->campaign->id() ?>/message"
         title="Compose <?= $this->campaign->name ?>"
         class="btn btn-info">Compose</a>
      <?php if($ds && $ds->hasAttributes()): ?>
        <a href="/campaigns/<?= $this->campaign->id() ?>/source"
           title="Edit Data Source"
           class="btn btn-info">Data Source</a>
      <?php endif ?>
    </div>
    <div class="btn-group">
      <a href="/campaigns/<?= $this->campaign->id() ?>/delete"
         title="Delete <?= $this->campaign->name ?>"
         class="js-popover btn btn-danger"
         data-content="<?= $this->getDeletePopover($this->campaign->id()) ?>"
         data-placement="bottom"
         data-html="true" data-container="body"
         data-prevent-default="true">Delete</a>
      <a href="/campaigns/<?= $this->campaign->id() ?>/clone"
         class="btn btn-warning">Clone</a>
      <a href="/campaigns/new" class="btn btn-primary">New</a>
    </div>
    <div class="btn-group">
      <a href="/campaigns/<?= $this->campaign->id() ?>/test"
         title="Test <?= $this->campaign->name ?>"
         class="btn btn-primary">Test</a>
    </div>
    <div class="btn-group">
      <a href="/campaigns/<?= $this->campaign->id() ?>/send"
         title="Send <?= $this->campaign->name ?>"
         class="js-popover btn btn-success"
         data-content="<?=
         $this->getConfirmPopover(
           '/campaigns/' . $this->campaign->id() . '/send'
         ) ?>"
         data-placement="bottom"
         data-html="true" data-container="body"
         data-prevent-default="true">Queue Campaign</a>
    </div>
  </div>
  <div>
    <h3><?= $this->campaign->name ?></h3>
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><?= $this->campaign->name ?></dd>
      <dt>Reference</dt>
      <dd><?= $this->campaign->reference ?></dd>
      <dt>Data Source</dt>
      <dd><?php
        if($ds)
        {
          echo $ds->getName();
        }
        ?></dd>
      <dt>Send Type</dt>
      <dd><?= $this->campaign->getTitledSendType() ?></dd>
      <dt>Description</dt>
      <dd><?= $this->campaign->description ? : "<em>Not Set</em>" ?></dd>
      <dt>Contact</dt>
      <dd><a href="/contacts/<?= $this->campaign->contactId ?>"
             title="View <?= $this->campaign->getContact()->name ?>">
          <?= $this->campaign->getContact()->name ?>
        </a></dd>
      <dt>Last Run</dt>
      <dd><?=
        $this->campaign->lastSent ?
          (new \DateTime())->setTimezone(new DateTimeZone('UTC'))
            ->setTimestamp($this->campaign->lastSent)
            ->format('d M Y H:i:sA')
          : 'Never'; ?></dd>
      <dt>Next Run</dt>
      <dd><?=
        ($nr = $this->campaign->nextRun()) ? $nr->setTimezone(
          new DateTimeZone('UTC')
        )->format('d M Y H:i:sA')
          : 'Never'; ?></dd>
      <dt>Active</dt>
      <dd><?= $this->campaign->active ? "Yes" : "No (Test Mode)" ?></dd>
    </dl>
  </div>
  <div class="stat50wrapper pull-left">
    <div class="well" style="height:120px; margin-right:5px;">
      <h3>24hr Statistics</h3>
      <?php
      echo '<span style="float:left;margin-right:20px" id="spark24h"'
        . ' data-max-queued="' . max($this->getQueued('24h')) . '"'
        . ' data-max-test="' . max($this->getTest('24h')) . '"'
        . ' data-max-sent="' . max($this->getSent('24h')) . '"'
        . ' data-max-failed="' . max($this->getFailed('24h')) . '"'
        . ' data-queued="' . implode(',', $this->getQueued('24h')) . '"'
        . ' data-test="' . implode(',', $this->getTest('24h')) . '"'
        . ' data-sent="' . implode(',', $this->getSent('24h')) . '"'
        . ' data-failed="' . implode(',', $this->getFailed('24h')) . '"'
        . '></span>';
      ?>
      <div>Total Queued: <?=
        number_format(
          $this->getTotalQueued('24h')
        ) ?></div>
      <div>Total Test: <?= number_format($this->getTotalTest('24h')) ?></div>
      <div>Total Sent: <?= number_format($this->getTotalSent('24h')) ?></div>
      <div>Total Failed: <?=
        number_format(
          $this->getTotalFailed('24h')
        ) ?></div>
    </div>
  </div>
  <div class="stat50wrapper pull-left">
    <div class="well" style="height: 120px;">
      <h3>30days Statistics</h3>
      <?php
      echo '<span style="float:left;margin-right:20px" id="spark30d"'
        . ' data-max-queued="' . max($this->getQueued('30d')) . '"'
        . ' data-max-test="' . max($this->getTest('30d')) . '"'
        . ' data-max-sent="' . max($this->getSent('30d')) . '"'
        . ' data-max-failed="' . max($this->getFailed('30d')) . '"'
        . ' data-queued="' . implode(',', $this->getQueued('30d')) . '"'
        . ' data-test="' . implode(',', $this->getTest('30d')) . '"'
        . ' data-sent="' . implode(',', $this->getSent('30d')) . '"'
        . ' data-failed="' . implode(',', $this->getFailed('30d')) . '"'
        . '></span>';
      ?>
      <div>Total Queued: <?=
        number_format(
          $this->getTotalQueued('30d')
        ) ?></div>
      <div>Total Test: <?= number_format($this->getTotalTest('30d')) ?></div>
      <div>Total Sent: <?= number_format($this->getTotalSent('30d')) ?></div>
      <div>Total Failed: <?=
        number_format(
          $this->getTotalFailed('30d')
        ) ?></div>
    </div>
  </div>
  <div class="clearfix"></div>
  <div>
    <?php
    $cpv = new CampaignProcessorsView($this->campaign);

    $controller = clone $this->getHostController();
    $controller->setBaseUri(
      sprintf("/campaigns/%d/processors", $this->campaign->id())
    );
    echo $cpv->setHostController($controller)
    ?>
  </div>
</div>
