<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Campaigns\CampaignsView
 */
?>
<div class="wrappedContent">
  <div>
    <div class="pull-right">
      <a href="/campaigns/new" class="btn btn-primary btn-small">
        New Campaign
      </a>
    </div>
    <?= $this->campaignsSearch ?>
  </div>
  <div>
    <table class="table table-striped table-bordered table-hover table-href">
      <caption><?= $this->pagerInfo ?></caption>
      <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Reference</th>
        <th>Data Source</th>
        <th>Send Type</th>
        <th>Active</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <?php foreach($this->campaigns as $campaign): ?>
        <tr data-href="/campaigns/<?= $campaign->id() ?>"
            class="js-href"
            title="View <?= $campaign->name ?>">
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>"
               title="View <?= $campaign->name ?>">
              #<?= $campaign->id() ?>
            </a>
          </td>
          <td><?= $campaign->name ?></td>
          <td><?= $campaign->reference ?></td>
          <td><?=
            $campaign->dataSource() ?
            $campaign->dataSource()->getName() : ''; ?></td>
          <td><?= $campaign->getTitledSendType() ?></td>
          <td><?= $campaign->active ? "Yes" : "No" ?></td>
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>/edit"
               title="Edit <?= $campaign->name ?>">
              <i class="icon-edit"></i></a>
            <a href="/campaigns/<?= $campaign->id() ?>/delete"
               title="Delete <?= $campaign->name ?>"
               class="js-popover"
               data-content="<?= $this->getDeletePopover($campaign->id()) ?>"
               data-html="true"
               data-prevent-default="true"
               data-placement="left">
              <i class="icon-trash"></i></a>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <div><?= $this->pager ?></div>
</div>
