<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\CampaignsView
 */
use Cubex\Facade\Session;
?>
<div class="wrappedContent">
  <?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type ?>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?= Session::getFlash('msg')->message ?>
  </div>
  <?php endif; ?>
  <div class="text-right">
    <a href="/campaigns/new" class="btn btn-primary btn-small">
      New Campaign
    </a>
  </div>
  <div>
    <table class="table table-striped table-bordered">
      <caption><?= $this->pagerInfo ?></caption>
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Reference</th>
          <th>Type</th>
          <th>Send Type</th>
          <th>Active</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->campaigns as $campaign): ?>
        <tr>
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>"
               title="View <?= $campaign->name ?>">
              #<?= $campaign->id() ?>
            </a>
          </td>
          <td><?= $campaign->name ?></td>
          <td><?= $campaign->reference ?></td>
          <td><?= $campaign->getTitledType() ?></td>
          <td><?= $campaign->getTitledSendType() ?></td>
          <td><?= $campaign->active ? "Yes" : "No" ?></td>
          <td>
            <a href="/campaigns/<?= $campaign->id() ?>/edit"
               title="Edit <?= $campaign->name ?>">
              <i class="icon-edit"></i></a>
            <a href="/campaigns/<?= $campaign->id() ?>/delete"
               title="Delete <?= $campaign->name ?>"
               class="js-popover"
               data-content="<?= $this->getDeletePopover($campaign->id()) ?>"
               data-html="true"
               data-prevent-default="true">
              <i class="icon-trash"></i></a>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <div><?= $this->pager ?></div>
</div>
