<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\CampaignView
 */
?>
<div class="wrappedContent">
  <div class="pull-right btn-group">
    <a href="/campaigns/<?= $this->campaign->id() ?>/edit"
       title="Edit <?= $this->campaign->name ?>"
       class="btn btn-info">Edit</a>
    <a href="/campaigns/<?= $this->campaign->id() ?>/delete"
       title="Delete <?= $this->campaign->name ?>"
       class="js-popover btn btn-danger"
       data-content="<?= $this->getDeletePopover($this->campaign->id()) ?>"
       data-placement="bottom"
       data-html="true"
       data-prevent-default="true">Delete</a>
    <a href="/campaigns/new" class="btn btn-primary">
      New</a>
  </div>
  <div>
    <h3><?= $this->campaign->name ?></h3>
  </div>
  <div>
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><?= $this->campaign->name ?></dd>
      <dt>Reference</dt>
      <dd><?= $this->campaign->reference ?></dd>
      <dt>Type</dt>
      <dd><?= $this->campaign->getTitledType() ?></dd>
      <dt>Send Type</dt>
      <dd><?= $this->campaign->getTitledSendType() ?></dd>
      <dt>Active</dt>
      <dd><?= $this->campaign->active ? "Yes" : "No" ?></dd>
      <dt>Description</dt>
      <dd><?= $this->campaign->description ? : "<em>Not Set</em>" ?></dd>
      <dt>Default Contact</dt>
      <dd><?= $this->contacts[$this->campaign->contactId]->name ?></dd>
    </dl>
  </div>
  <div>
    <h4>Contacts</h4>
  </div>
  <div>
    <?= $this->getContactsView() ?>
  </div>
</div>
