<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\ContactFormView
 */
?>
<div class="wrappedContent">
  <div class="alert alert-<?= Session::getFlash('msg')->type ?>">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <?= Session::getFlash('msg')->message ?>
  </div>
  <div>
    <h2 class="text-center">
      Contact Form
    </h2>
  </div>
  <?= $this->contactForm ?>
</div>
