<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\ProcessorView
 */
?>
<div class="wrappedContent">
  <div class="pull-right btn-group">
    <a href="/processors/<?= $this->processor->id() ?>/edit"
       title="Edit <?= $this->processor->name ?>"
       class="btn btn-info">Edit</a>
    <a href="/processors/<?= $this->processor->id() ?>/delete"
       title="Delete <?= $this->processor->name ?>"
       class="js-popover btn btn-danger"
       data-content="<?= $this->getDeletePopover($this->processor->id()) ?>"
       data-placement="bottom"
       data-html="true"
       data-prevent-default="true">Delete</a>
    <a href="/processors/new" class="btn btn-primary">
      New</a>
  </div>
  <div>
    <h3><?= $this->processor->name ?></h3>
  </div>
  <div>
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><?= $this->processor->name ?></dd>
      <dt>Config</dt>
      <dd><?= $this->processor->config ?></dd>
      <dt>Description</dt>
      <dd><?= $this->processor->description ?></dd>
    </dl>
  </div>
</div>
