<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Contacts\ContactsView
 */
?>
<div class="wrappedContent">
  <?php if(!$this->tableOnly()): ?>
  <div>
    <div class="pull-right">
      <a href="/contacts/new" class="btn btn-primary btn-small">
        New Contact
      </a>
    </div>
    <?= $this->contactsSearch ?>
  </div>
  <?php endif; ?>
  <div>
    <table class="table table-striped table-bordered table-hover table-href">
      <caption><?= $this->pagerInfo ?></caption>
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Reference</th>
          <th>Email</th>
          <th>Job Title</th>
          <th>Language</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach($this->contacts as $contact): ?>
        <tr data-href="<?= $this->baseUri() ?>/<?= $contact->id() ?>"
            class="js-href"
            title="View <?= $contact->name ?>">
          <td>
            <a href="<?= $this->baseUri() ?>/<?= $contact->id() ?>"
               title="View <?= $contact->name ?>">
              #<?= $contact->id() ?>
            </a>
          </td>
          <td><?= $contact->name ?></td>
          <td><?= $contact->reference ?></td>
          <td><?= $contact->email ?></td>
          <td><?= $contact->jobTitle ?></td>
          <td><?= $contact->language ?></td>
          <td>
            <a href="<?= $this->baseUri() ?>/<?= $contact->id() ?>/edit"
               title="Edit <?= $contact->name ?>">
              <i class="icon-edit"></i></a>
            <a href="<?= $this->baseUri() ?>/<?= $contact->id() ?>/delete"
               title="Delete <?= $contact->name ?>"
               class="js-popover"
               data-content="<?= $this->getDeletePopover($contact->id()) ?>"
               data-html="true"
               data-prevent-default="true"
               data-placement="left">
              <i class="icon-trash"></i></a>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>
  <div><?= $this->pager ?></div>
</div>
