<?php
/**
 * @author gareth.evans
 *
 * @var $this \Qubes\Defero\Applications\Defero\Views\Contacts\ContactView
 */
?>
<div class="wrappedContent">
  <div class="pull-right btn-group">
    <a href="/contacts/<?= $this->contact->id() ?>/edit"
       title="Edit <?= $this->contact->name ?>"
       class="btn btn-info">Edit</a>
    <a href="/contacts/<?= $this->contact->id() ?>/delete"
       title="Delete <?= $this->contact->name ?>"
       class="js-popover btn btn-danger"
       data-content="<?= $this->getDeletePopover($this->contact->id()) ?>"
       data-placement="bottom"
       data-html="true"
       data-prevent-default="true">Delete</a>
    <a href="/contacts/new" class="btn btn-primary">
      New</a>
  </div>
  <div>
    <h3><?= $this->contact->name ?></h3>
  </div>
  <div>
    <dl class="dl-horizontal">
      <dt>Name</dt>
      <dd><?= $this->contact->name ?></dd>
      <dt>Reference</dt>
      <dd><?= $this->contact->reference ?></dd>
      <dt>Email</dt>
      <dd><?= $this->contact->email ?></dd>
      <dt>Job Title</dt>
      <dd><?= $this->contact->jobTitle ?></dd>
      <dt>Language</dt>
      <dd><?= $this->contact->language ?></dd>
      <dt>Signature</dt>
      <dd><?= nl2br($this->contact->signature) ?></dd>
      <dt>Description</dt>
      <dd><?= $this->contact->description ? : "<em>Not Set</em>" ?></dd>
    </dl>
  </div>
</div>
